### PR TITLE
Added SPST switch to schematic viewer

### PR DESCRIPTION
**Pull request by abhijitxy**
- [x] Symbol in [tscircuit/schematic-viewer](https://github.com/tscircuit/schematic-viewer)

### CODE REVIEW

**Comment by abhijitxy** [comment]
@seveibar review!!

**Review by seveibar — CHANGES_REQUESTED** [review]
take a look at how other components are defined https://github.com/tscircuit/schematic-viewer/blob/main/src/schematic-components/SimpleCapacitor.tsx

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
Wait for checks before merging

**Comment by seveibar** [comment]
Are you able to see the storybook @abhijitxy ? Seems like you need to update or make additions to [tscircuit/react-fiber](https://github.com/tscircuit/react-fiber)

image

**Pull request closed without merging**
