### PR TITLE
Feat/manufacturer part number

### PR DESCRIPTION
**Pull request by imrishabh18**
Closes - https://github.com/tscircuit/tscircuit/issues/262

Screenshot 2024-07-21 at 12 02 07 AM

### CODE REVIEW

**Comment by imrishabh18** [comment]
@seveibar Seems like even the schematic viewer will need some refactoring cause, the types which are getting used are not in sync with the latest packages. 😅

**Review by seveibar — APPROVED** [review]
nice, yea i think it will only release if we fix the type issues (I don't think they look too bad 😬 )

**Comment by seveibar** [comment]
Side note: the visual regression worked!

image

**Comment by imrishabh18** [comment]
This will be super helpful 🚀

**Comment by imrishabh18** [comment]
@seveibar The typecheck is not failing in my local but it is here, I think it's because the latest soup build is not getting fetched here. I think this can be merged cause after the latest soup this will pass as well.
Screenshot 2024-07-22 at 9 57 12 AM

**Comment by seveibar** [comment]
@imrishabh18 just checking did you try `npm i` to get the latest versions of the deps?

**Comment by seveibar** [comment]
to upgrade the soup remotely you could do `npm add @tscircuit/soup@latest`

**Comment by seveibar** [comment]
FWIW i get a type error:

image

**Comment by imrishabh18** [comment]
The `manufacturerPartNumber` has been added in the soup and merged now, I will take a look at this.

**Comment by imrishabh18** [comment]
All green 🟢

**Review by seveibar — APPROVED** [review]
🚀

**Comment by imrishabh18** [comment]
Taken care of the UI regression. Apologies, for these many to and fro

**Review by seveibar — APPROVED** [review]
im so happy the visual regression tests were helpful, they've already paid off in less than a couple days!!!!

**Pull request merged**
