### PR TITLE
Refactor builder with core & Update the schematic viewer (WIP)

### PR DESCRIPTION
**Pull request by imrishabh18**
I would say this still needs some work regarding refactoring the structure. But mostly from the `core` side, things which needs to be implemented over there and bug fixes in there.

Screenshot 2024-10-19 at 4 32 18 AM

PS: A very tiny PR to review @seveibar 😂

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
Nice work!

**Comment by seveibar** [comment]
Will play with this a bit later! Huge PR!!

**Comment by imrishabh18** [comment]
@seveibar We will merge when all the changes are fixed on core for this, or we can merge this now with some things broken and incrementally work on core?

**Comment by seveibar** [comment]
@imrishabh18 i think we can merge and work incrementally on core, it's basically useless while it uses builder

**Pull request merged**
